# Generated by Django 4.0.3 on 2022-03-27 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_news_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='category_id',
            new_name='category',
        ),
    ]
