# Generated by Django 4.0.3 on 2022-03-27 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_news_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='news.category'),
        ),
    ]
